### PR TITLE
feat: Add a method to validate a specific mnemonic word

### PR DESCRIPTION
**Pull request by redDwarf03**

### CODE REVIEW

**Comment by ethicnology** [comment]
@redDwarf03 thanks for your interest in this project.

[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) introduce a normalization for label, can you amend your commit in order to rename it ```feat: Add a method to validate a specific menmonic word``` :  
```sh
git commit --amend
git push -ff
```

**Comment by ethicnology** [comment]
Actually, when someone tries to instance a new mnemonic with a non-valid word, it [throws an exception](https://github.com/ethicnology/dart-bip39-mnemonic/blob/main/lib/src/mnemonic.dart#L104=).

@redDwarf03  May I ask you in which situation do you need this kind of feature?

Maybe you have multiples TextFormEdit that represents each word of the sentence in your flutter project, and you need a simple validator function for each of them ?

**Comment by redDwarf03** [comment]
> Maybe you have multiples TextFormEdit that represents each word of the sentence in your flutter project, and you need a simple validator function for each of them ?

yes, when the user enters his words one by one, I want to inform him if a word is not valid

**Comment by ethicnology** [comment]
Ok pushed a refactor with isValid as a method of the Language enum.
```dart
var english = Language.english;
english.isValid('baguette'); //false
```

I already did a component using Autocomplete widget to recompose a BIP39 seed, please take care about NFKD formatting which is mandatory in BIP39.

@redDwarf03 You should read this issue https://github.com/flutter/flutter/issues/104927#issuecomment-1141319254

```dart
// https://github.com/flutter/flutter/issues/104927#issuecomment-1141319254
test('check if word is NFKD, no', () {
  expect(Language.french.isValid('échelle'), false); // non NFKD
});

test('check if word is NFKD, yes', () {
  expect(Language.french.isValid('échelle'), true); // NFKD
});
```

**Comment by redDwarf03** [comment]
Thank you @ethicnology for your precious help. I will wait for the pub.dev update

**Pull request merged**
